#!/usr/bin/env bash
echo "Running detekt check..."
OUTPUT=$(mktemp "detekt-XXXXX")
./gradlew detekt > "$OUTPUT"
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat "$OUTPUT"
  rm "$OUTPUT"
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit 1
else
  echo "***********************************************"
  echo "                 detekt success                "
  echo "***********************************************"
  cat "$OUTPUT"
  rm "$OUTPUT"
fi